{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pov-sim.fullname" . }}
  labels:
    {{- include "pov-sim.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "pov-sim.componentFullname" (dict "root" $ "component" .service) }}
                port:
                  number: {{- if eq .service "frontend" }} {{ $.Values.frontend.service.port }}{{- else if eq .service "airlines" }} {{ $.Values.airlines.service.port }}{{- else }} {{ $.Values.flights.service.port }}{{- end }}
          {{- end }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
