apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pov-sim.secretName" . }}
  labels:
    {{- include "pov-sim.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLOUD_OTLP_ENDPOINT: {{ .Values.secrets.cloudOtlpEndpoint | quote }}
  CLOUD_OTLP_USERNAME: {{ .Values.secrets.cloudOtlpUsername | quote }}
  CLOUD_OTLP_PASSWORD: {{ .Values.secrets.cloudOtlpPassword | quote }}
  PYROSCOPE_SERVER_ADDRESS: {{ .Values.secrets.pyroscopeServerAddress | quote }}
  PYROSCOPE_BASIC_AUTH_USER: {{ .Values.secrets.pyroscopeBasicAuthUser | quote }}
  PYROSCOPE_BASIC_AUTH_PASSWORD: {{ .Values.secrets.pyroscopeBasicAuthPassword | quote }}
